# https://docs.github.com/en/enterprise-server@2.22/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Maven Project CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
          architecture: x64
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package